### ISSUE TITLE
Got error when training with S3DIS: "RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx"

### ISSUE THREAD

**Issue by tkm-n** [Yukichiii/Swin3D_Task#2]
Thank you for sharing a promising model. I'm now testing this repo with S3DIS following the instructions in the repo, but I got the following error. It seems to be caused by the wrong input dimension. Do you have any idea to solve this?

> [09/09 09:28:13 main-logger]: #Model parameters: 26495773
> [09/09 09:28:14 main-logger]: => no checkpoint found at 'runs/s3dis_Swin3D_RGB_S_123/model/model_last.pth'
> [09/09 09:28:14 main-logger]: augmentation all
> [09/09 09:28:14 main-logger]: jitter_sigma: 0.005, jitter_clip: 0.02
> Totally 204 samples in train set.
> Total repeated 204 samples in train set.
> [09/09 09:28:14 main-logger]: train_data samples: '1224'
> /home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/dataloader.py:563: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
>   warnings.warn(_create_warning_msg(
> Totally 67 samples in val set.
> Total repeated 67 samples in val set.
> [09/09 09:28:14 main-logger]: scheduler: MultiStep. scheduler_update: epoch. milestones: [60, 80], gamma: 0.1
> [09/09 09:28:14 main-logger]: lr: [0.0006, 5.9999999999999995e-05]
> feat:  torch.Size([80000, 3])
> /home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1659484683044/work/aten/src/ATen/native/TensorShape.cpp:2894.)
>   return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
> /home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/modules/swin3d_layers.py:783: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
>   w_w_id // window_size // window_size,
> /home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/modules/swin3d_layers.py:784: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
>   w_w_id // window_size % window_size,
> feats.shape:  torch.Size([80000, 48])
> Traceback (most recent call last):
>   File "SemanticSeg/train.py", line 916, in <module>
>     main()
>   File "SemanticSeg/train.py", line 114, in main
>     main_worker(args.train_gpu, args.ngpus_per_node, args)
>   File "SemanticSeg/train.py", line 510, in main_worker
>     loss_train, mIoU_train, mAcc_train, allAcc_train = train(
>   File "SemanticSeg/train.py", line 606, in train
>     output = model(feat, coord, batch)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/Swin3D/SemanticSeg/model/Swin3D_RGB.py", line 70, in forward
>     return self.backbone(sp, coords_sp)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/models/Swin3D.py", line 140, in forward
>     sp, sp_down, coords_sp = layer(sp, coords_sp)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/modules/swin3d_layers.py", line 866, in forward
>     feats = blk(feats, attn_args_blk)  # [N, C]
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/modules/swin3d_layers.py", line 622, in forward
>     feats = self.attn(feats, attn_args)  # [N, c]
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/Swin3D-0.0.0-py3.8-linux-x86_64.egg/Swin3D/modules/swin3d_layers.py", line 504, in forward
>     qkv = self.qkv(feats)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/home/ubuntu/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
>     return F.linear(input, self.weight, self.bias)
> RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

As far as I checked, [Window Attention](https://github.com/microsoft/Swin3D/blob/4184679dbdf35340a10823a7d12b9a7c0381d3e5/Swin3D/modules/swin3d_layers.py#L382) in the first block seems waiting 48 dimensional data, but it gets 80000 dimensional data.

**Comment by tkm-n** [comment]
Sorry, I was wrong. The input data is [80000, 48] and the layer is nn.Linear(48, 144, bias=True), so it seems correct. 
If you have any idea about the error which I got, please let me know.

**Comment by tkm-n** [comment]
Sorry again, this error seems not related to this repository but related to GPU memory or cuda version, etc. I could solve this through updating Cuda, pytorch, cudnn.
